### ISSUE TITLE
Error Running on Runpod via CLI

### ISSUE THREAD

**Issue by ChrGriffin** [JoePenna/Dreambooth-Stable-Diffusion#100]
I've been trying to get this working via the CLI on a Runpod instance so I can run it more or less as a service. However, when running via CLI, I get an error that I'm not quite sure how to solve.

The command I run, via SSH, is (I've changed the project directory name):

`nohup python3.8 /workspace/dreambooth/main.py --base '/workspace/dreambooth/configs/stable-diffusion/v1-finetune_unfrozen.yaml' -t --actual_resume 'model.ckpt' --reg_data_root '/workspace/dreambooth/regularization_images/person_ddim' -n '<name>' --gpus 1 --data_root '/workspace/dreambooth/training_images' --max_training_steps 4000 --class_word 'person' --token '<token>' --no-test > '/workspace/dreambooth/training.out'`

The process begins booting up fine, but once it starts trying to train, I get this error:

`Traceback (most recent call last):
  File "/workspace/dreambooth/main.py", line 828, in <module>
    ngpu = len(lightning_config.trainer.gpus.strip(",").split(','))
AttributeError: 'int' object has no attribute 'strip'`

So, clearly it's expecting a `string` but receiving an `int`. I just don't know why. This same script works fine when I run it from the Jupyter Lab interface, so it must be some sort of difference between that and the CLI. Unfortunately, I simply don't know enough about Jupyter to guess at what that could be.

Any ideas?

**Comment by SWivid** [comment]
you can simply change `--gpus 1` to `--gpus 1,` so as to put in this parameter as a str

**Comment by ChrGriffin** [comment]
Yup, that's a face slapper for me. Thanks!
