### ISSUE TITLE
pip install step not working on Vast.ai HTTPS

### ISSUE THREAD

**Issue by CaptainValor** [JoePenna/Dreambooth-Stable-Diffusion#11]
Running Jupyter on Vast.ai [in proxy mode is *very* slow ](https://vast.ai/faq/#Jupyter)(download for 2GB often takes several hours, aka. $3-4). Is there a way to get this running on Vast.ai's HTTPS mode? I get the following error when trying to set up the environment:

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/omegaconf/`

It seems to have something to do with pypi.org preferring IPv4 over IPv6, but I couldn't get around it.

**Comment by djbielejeski** [comment]
I just tested this via the https mode and it is working fine, you might have a bad vast.ai instance.

![image](https://user-images.githubusercontent.com/2463282/193145685-f4da313a-1df0-4598-804a-b31c3e86c6f5.png)
