### ISSUE TITLE
How to provide negative prompt?

### ISSUE THREAD

**Issue by obaid** [JoePenna/Dreambooth-Stable-Diffusion#116]
When called stable_txt2img, how do I pass negative prompt?

**Comment by AlexanderKozhevin** [comment]
Yeap, interesting too

**Comment by burak-yilmaz** [comment]
I'm also trying to provide negative prompts using Dreambooth but so fa my attempts have failed. I would like to believe there is a small trick 🙏🏼

**Comment by brentperry** [comment]
You can put it in square brackets to negate an option like " [glasses], myperson person, portrait" to remove someone's glasses for instance. The earlier in the phase the more weight the phrase gets apparently.
