### ISSUE TITLE
Training step cell in jupyter lab not showing progress output

### ISSUE THREAD

**Issue by artgadliba** [JoePenna/Dreambooth-Stable-Diffusion#119]
Hello!
I have encountered an issue,  where I cant see any progress output while training process is calculating. It shows only after execution is complete. Im working in Jupyter Lab run locally on Windows Server 2022.
Any ideas how to fix it?

**Comment by hopto-dot** [comment]
Same issue here @JoePenna !

I'm locally running the **Training** cell and my Cuda usage is hovering around 65% with 23.6gb of VRAM being dedicated to training. Also, I can see new last.ckpt and global step sample images being generated every roughly 11 minutes so I know the training is working.

@artgadliba are you still having issues?
