### ISSUE TITLE
"Nothing" works 😫

### ISSUE THREAD

**Issue by Kallamamran** [JoePenna/Dreambooth-Stable-Diffusion#12]
Well... Running the notebook I get this from the second cell:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.0 which is incompatible.
tb-nightly 2.11.0a20220905 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.0 which is incompatible.
google-api-core 2.10.1 requires protobuf<5.0.0dev,>=3.20.1, but you have protobuf 3.20.0 which is incompatible.

Later in the same log:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wandb 0.13.2 requires protobuf<4.0dev,>=3.12.0, but you have protobuf 4.21.7 which is incompatible.
tensorboard 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.7 which is incompatible.
tb-nightly 2.11.0a20220905 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.7 which is incompatible.
streamlit 1.12.2 requires protobuf<4,>=3.12, but you have protobuf 4.21.7 which is incompatible.
pytorch-lightning 1.6.5 requires protobuf<=3.20.1, but you have protobuf 4.21.7 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-core 2.10.1 requires protobuf<5.0.0dev,>=3.20.1, but you have protobuf 3.19.5 which is incompatible.

Nothing I do helps. I tried running it on RunPod and locally in my computer with the same result 😥

**Comment by djbielejeski** [comment]
For help actually running this, checkout the [discord](https://discord.com/invite/qbMuXBXyHA)
