### ISSUE TITLE
Best way to use my own regulization images

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [JoePenna/Dreambooth-Stable-Diffusion#120]
Hello, I attempted to upload my regulation images but get an error when I remove the data set or even run it.

I got all mine in the git hub. 

Do you know the best way to be able to possibly use these images I do below?

Uploaded to GitHub

Start notebook run down the list then once I put it in regulation images it does not let me just errors

**Comment by hsbsid** [comment]
Where are you running the notebook?
