### ISSUE TITLE
torch.cuda.OutOfMemoryError: on AWS p3.8xlarge

### ISSUE THREAD

**Issue by XavaarQ** [JoePenna/Dreambooth-Stable-Diffusion#122]
I'm getting the following error when I run the training cell in dreambooth_runpod_joepenna.ipynb

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.44 GiB already allocated; 8.19 MiB free; 14.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I'm running this on my own aws p3.8xlarge instance. Does anyone know whether this is a configuration problem or whether this type instance has insufficient specs?

**Comment by geocine** [comment]
You should have at least 24GB vram
