### ISSUE TITLE
RuntimeError: Input type (c10::Half) and bias type (float) should be the same - Google Colab

### ISSUE THREAD

**Issue by tclass** [JoePenna/Dreambooth-Stable-Diffusion#127]
got a Google Colab error when I try to run the training anyone has the same issues?

![Screenshot 2022-12-20 at 22 18 28](https://user-images.githubusercontent.com/821322/208768864-5c0b8835-fe35-4cb8-b327-2aa1b3db731a.png)

**Comment by tclass** [comment]
I somehow fixed it while changing this
`vae.decoder.to("cpu")`
to
`vae.decoder.to("cuda")`

**Comment by tam9life** [comment]
vae.decoder.to("cpu") location

colab/ Teach the model the new concept (fine-tuning with Dreambooth)/ Training Fuction/ show code/ find "cpu" > line 113
