### ISSUE TITLE
Runpod Javascript error # Hugging Face Login

### ISSUE THREAD

**Issue by DanielSpacek** [JoePenna/Dreambooth-Stable-Diffusion#134]
Hi, I am getting this Javascript error in the Hugging Face login cel, when running on Runpod.
It was working flawlessly until yesterday, never had an issue with that. many successful trainings performed :D. Thanks to all of you that made this amazing tool happen btw.

To be really honest, I am a noob user, this is probably way over my technical knowledge.
Did anyone experience the same issue?

Thanks.

Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
    at f.loadClass (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74977)
    at f.loadModelClass (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729)
    at f._make_model (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517)
    at f.new_model (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:5137)
    at f.handle_comm_open (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:3894)
    at _handleCommOpen (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:73393)
    at b._handleCommOpen (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/static/lab/jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1001335)
    at async b._handleMessage (https://paqpkc1xtdi2xz-8888.proxy.runpod.net/static/lab/jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1003325)

**Comment by dmitrii-brand** [comment]
Same here

**Comment by dmitrii-brand** [comment]
As a temp fix, changed this line in requirements:

```
pip install huggingface_hub==0.11.0
```

**Comment by DanielSpacek** [comment]
> pip install huggingface_hub==0.11.0

Thank you. I have tried that, but unfortunately, the error persists. I even tried the other  huggingface_hub packages, same result. Have you done anything else?

**Comment by dmitrii-brand** [comment]
You have to rerun all the cells from the start and it would work. The issue is with latest hub release.

**Comment by DanielSpacek** [comment]
> pip install huggingface_hub==0.11.0

by requirements, you mean the pip installing in the cell #BUILD ENV in section Build environment?

I have typed it there exactly, replacing the old huggingface_hub

This is what i get and unfortunately the javascript error persists :(
do you please have any idea what am I doing wrong? Many thanks for your help, I am very noob in this :D

Collecting huggingface_hub==0.11.0
  Downloading huggingface_hub-0.11.0-py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.1/182.1 kB 11.7 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (22.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (2.28.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (3.9.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (4.4.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from huggingface_hub==0.11.0) (4.64.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub==0.11.0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface_hub==0.11.0) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface_hub==0.11.0) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface_hub==0.11.0) (1.26.13)
Installing collected packages: huggingface_hub
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.11.1
    Uninstalling huggingface-hub-0.11.1:
      Successfully uninstalled huggingface-hub-0.11.1
Successfully installed huggingface_hub-0.11.0

**Comment by 0gucio0** [comment]
Hi guys, it seems like the temp fix doesn't work. I'm still getting the same errors even with it already in the # BUILD ENV section. Maybe there was another update.

**Comment by phutngo** [comment]
I have the same issue.

![joepenna issue](https://user-images.githubusercontent.com/13474246/210262595-ced15e51-1a54-4beb-b489-5b414f534104.jpg)

**Comment by techsteramman** [comment]
same here

**Comment by Hades32** [comment]
Just ignore the login cell and in `use_auth_token=True` replace the `True` with a string of your HF token

**Comment by techsteramman** [comment]
this didn't fix the underlying issue. other parts of the code weren't functioning as expected too

**Comment by DanielSpacek** [comment]
Hey guys, I have found working workaround. When launching runpod, select version with SD 1.5. Then you can copy ckpt file directly. Rest of the process worked ok, I already did few training rounds.
Credits and issue solving you might experience with memory goes to: https://www.youtube.com/watch?v=A3iiBvoC3M8 .

**Comment by umeshukla** [comment]
could please be more specific. How to launch pod with 1.5 and then how to copy ckpt file directly? 
Thanks

**Comment by hansheng654** [comment]
just use a different login func.....
`# Hugging Face Login
from huggingface_hub import interpreter_login

interpreter_login()`

**Comment by djbielejeski** [comment]
This has been resolved.
