### ISSUE TITLE
Missing Python modules to RunPod.io Jupyter notebook

### ISSUE THREAD

**Issue by bennycheung** [JoePenna/Dreambooth-Stable-Diffusion#139]
For bug fix, the RunPod.io Jupyter notebook is missing some Python modules to run successfully. Please add the following into the "BUILD DEV" cell that doing `pip install` with the following missing modules:

```
!pip install taming-transformers-rom1504
!pip install clip
```

**Comment by OoAnikioO** [comment]
these missing modules prevent what?

**Comment by bennycheung** [comment]
The algorithm used in `main.py` will not execute without these modules.

**Comment by caniyabanci76** [comment]
The default notebook runs just fine in Vast.ai.  So no changes required there. I have not tried it on runpod.io

**Comment by djbielejeski** [comment]
@bennycheung did you test the changes in Vast.AI to make sure that isn't broken with these changes?
