### ISSUE TITLE
training gets "Killed" ? not sure why

### ISSUE THREAD

**Issue by drfleetles** [JoePenna/Dreambooth-Stable-Diffusion#15]
I followed the steps in the video Aitrepreneur made and I keep coming across this error
![image](https://user-images.githubusercontent.com/77469527/193164895-0e5ddb26-c529-4ec9-a3fe-f5961ecd6eff.png)

Not sure what is happening

**Comment by Puremask** [comment]
Mine has also been doing this. Any fix you've found?

**Comment by thommorais** [comment]
same here!

**Comment by thommorais** [comment]
FIX FOUND:  In Jupyter Lab, open a new tab, open a terminal and type "ps aux" to find the POD for relauncher and webui, kill both process and restart the training.

**Comment by thommorais** [comment]
on the youtube there is a thread that are discussing this. https://www.youtube.com/watch?v=7m__xadX0z0&lc=UgzHSfUz5CihSyO8nzN4AaABAg.9gVbwSnCOg19gW16WBw0RG

**Comment by drfleetles** [comment]
![image](https://user-images.githubusercontent.com/77469527/193188648-c76f4300-f83d-4cb8-b987-4adffc723e9e.png)

**Comment by drfleetles** [comment]
![image](https://user-images.githubusercontent.com/77469527/193191767-f388ab9e-b08d-4d05-9e71-926bf452d1bc.png)

**Comment by 1blackbar** [comment]
you guys have even amount of pics? I had 64 on vast yesterday and trained till 2000 steps no issues

**Comment by roar-emaus** [comment]
Hey! I had the same problem several times, and this could just be a coincidence, but when using 2xGPUs and setting `--gpus 1` it runs all the way to the end.

**Comment by drfleetles** [comment]
> Same here... Worked before, stopped working. Now I have started from the beginning and now I get this:
> 
> Epoch 0: 0%| | 1/2020 [00:03<1:44:35, 3.11s/it, loss=0.0379, v_num=0, train/lHere comes the checkpoint... Killed
> 
> Yes: Even amount of images (0 to 19 = 20 pictures)

Try the first solution that I posted, the image of the YouTube comment

**Comment by drfleetles** [comment]
ok, someone commented on [Aitrepreneur](https://www.youtube.com/c/Aitrepreneur) latest video
<img width="515" alt="image" src="https://user-images.githubusercontent.com/77469527/193376340-817e9452-47fa-4e3a-a4b1-ae30153356cc.png">

**Comment by vlameiras** [comment]
> ok, someone commented on [Aitrepreneur](https://www.youtube.com/c/Aitrepreneur) latest video <img alt="image" width="515" src="https://user-images.githubusercontent.com/77469527/193376340-817e9452-47fa-4e3a-a4b1-ae30153356cc.png">

I did this and the issue persists with an A5000 on RunPod

**Comment by drfleetles** [comment]
> > ok, someone commented on [Aitrepreneur](https://www.youtube.com/c/Aitrepreneur) latest video <img alt="image" width="515" src="https://user-images.githubusercontent.com/77469527/193376340-817e9452-47fa-4e3a-a4b1-ae30153356cc.png">
> 
> I did this and the issue persists with an A5000 on RunPod

Sorry to hear that, it worked for me. Have you tried the first solution where you kill the programs?

**Comment by afleming2009** [comment]
could it be space on the machine?  i'm noticing this is happening when my volume runs out of space.

**Comment by vlameiras** [comment]
I did try to kill the processes as well. It ended up working when I tried using a community pod with an RTX 3900 gpu 😃

**Comment by witzatom** [comment]
Some extra info on this, as this is happening for me too.

Before running, check `nvidia-smi` in terminal, memory should be `1MiB / 24564MiB`, if its higher, you have to kill something.

But even then, i do get OOM kills. It is not after one iteration, its sometimes after a 100, sometimes after 200. This is very annoying as checkpointing right now is every 500. I am considering changing this to every 100 in my code so that I dont lose everything on these kills.

**Comment by ddevillier** [comment]
If running via runpod, run a PyTorch instance instead of a stable diffusion one. I stopped getting killed processes after that. Tested on 3090 and A5000.

**Comment by witzatom** [comment]
Yea, i always run pytorch instead of sd and i still have issues on the a5000, it seems its just random.

**Comment by urbanyeti** [comment]
Same experience as wizatom in the last few days.

**Comment by thatneat** [comment]
This worked for me. You can run it in a jupyter cell, no need to open a separate terminal:
```
!ps aux | grep 'webui\|relauncher' | head -3 | awk '{print $2}' | xargs kill -9
```
What that does:
```
ps aux # list processes
grep 'webui\|relauncher' # find the processes corresponding to webui and relauncher
head -3 # grab the first 3 lines (1 relauncher process and 2 webui processes). This may not be necessary
awk '{print $2}' # read the second column, which has the process ID
xargs kill -9 # pass the result to kill which will kill the processes.
```
When you run `ps aux` (or `!ps aux` in jupyter) afterwards, you should see no processes for webui or relauncher.

**Comment by Larcebeau** [comment]
thank you mate ! :)

**Comment by jwatzman** [comment]
For anyone running into this for which the above doesn't help, this can be caused by a number of things, but the most likely is due to the machine running out of RAM -- not VRAM, but traditional main RAM. (Pretty sure the out-of-VRAM error is quite different.) The above suggestions will indeed free up a good bit of RAM (probably VRAM too) which can/will help. But if you still have the problem try renting a machine with more RAM. (Or, if running locally, increasing swap space or upgrading your hardware.)

**Comment by hirad** [comment]
For me the issue on RunPod was that when you start a pod, by default, it's set to 0 GPUs. If you click through it mindlessly, you will encounter this issue. You must select 1x GPU when starting.
