### ISSUE TITLE
Name "dataset' no defined 

### ISSUE THREAD

**Issue by Bobo-Shaba** [JoePenna/Dreambooth-Stable-Diffusion#150]
I'm trying to train SD with my own images but I keep getting this error in training section
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_127/4096925038.py in <module>
     19 token = "BoboPerson"
     20 
---> 21 reg_data_root = "/workspace/Dreambooth-Stable-Diffusion/outputs/" + dataset
     22 
     23 get_ipython().system('rm -rf training_images/.ipynb_checkpoints')

NameError: name 'dataset' is not defined

**Comment by caniyabanci76** [comment]
you didn't run one of the regularization image cells that sets a variable named dataset which is used in the training cell as part of a folder path.  if you are providing your own reg. images then make sure that is set to whatever your folder name is

**Comment by Bobo-Shaba** [comment]
Thanks, I didn't realize i skipped a step but new errors keep popping up.

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from ldm.modules.pruningckptio.py import PruningCheckpointIO
ModuleNotFoundError: No module named 'ldm.modules.pruningckptio'

when I went through the Idm file 'ldm.modules.pruningckptio.py' does exist.

If I remove line 2 from main.py I get a different error (had no reason to remove it just annoyed)

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'

from ldm.modules.pruningckptio.py import PruningCheckpointIO

**Comment by caniyabanci76** [comment]
Then that means your ENV wasn't built properly or didn't finish.  pruningckptio.py is needed each time a checkpoint is created.  You're just going to make things worse by removing references to it thinking it will fix it. 

start again and make sure the BUILD ENV cell completes
