### ISSUE TITLE
StableDiffusionPipeline load pretrained models and learned_embeds_dict from different directories

### ISSUE THREAD

**Issue by arsalyou** [JoePenna/Dreambooth-Stable-Diffusion#156]
I want to save text_encoder, vae, unet, tokenizer and scheduler in a separate folder and learned_embeds_dict in a different directory and then load these models from their respective directory while calling StableDiffusionPipeline.from_pretrained.
The reason I want to do is to train models on different styles for each user and making sure we store text_encoder, vae, unet, tokenizer and scheduler only once and use it rather than downloading again in each training session

**Comment by djbielejeski** [comment]
You'll have to fork and modify on your own.
