### ISSUE TITLE
NameError: name 'trainer' is not defined

### ISSUE THREAD

**Issue by Stoops0311** [JoePenna/Dreambooth-Stable-Diffusion#163]
Global seed set to 23
Traceback (most recent call last):
  File "main.py", line 656, in <module>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "main.py", line 656, in <listcomp>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/Dreambooth-Stable-Diffusion/configs/stable-diffusion/v1-finetune_unfrozen_save_checkpoints_every_500_steps.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 932, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by AmaruEscalante** [comment]
+1

**Comment by carlosvsm2** [comment]
I have the exact same issue with the NameError: name 'trainer' is not defined. I am hoping someone can help soon...

**Comment by AmaruEscalante** [comment]
Guys I found the solution. We aren't following the instructions on the readme well enough. 
1. Select Pytorch as your template
<img width="1392" alt="Screenshot 2023-03-10 at 00 51 16" src="https://user-images.githubusercontent.com/46765459/224234430-ea2e884f-d9d7-452a-8722-bffa22e14d69.png">
2. Once you create it, edit the pod and remove all the versioning to just say `runpod/pytorch`, this I believe gets the latest version of the image, and voilá your code should run just fine.

**Comment by Stoops0311** [comment]
Nope sorry thats wrong, the problem i was having was becuase the repo itself was damaged it wasnt that we werent following the instructions i talked to the devs on discord they fixed the problem and changed some stuff, even the yaml script to save the models was missing before they fixed it dont worry but this is still a necessary step

**Comment by Stoops0311** [comment]
> Guys I found the solution. We aren't following the instructions on the readme well enough.
> 
> 1. Select Pytorch as your template
> 
> <img alt="Screenshot 2023-03-10 at 00 51 16" width="1392" src="https://user-images.githubusercontent.com/46765459/224234430-ea2e884f-d9d7-452a-8722-bffa22e14d69.png">
> 
> 2. Once you create it, edit the pod and remove all the versioning to just say `runpod/pytorch`, this I believe gets the latest version of the image, and voilá your code should run just fine.
> <img alt="Screenshot 2023-03-10 at 00 53 19" width="1084" src="https://user-images.githubusercontent.com/46765459/224234715-988df915-1cdb-4e10-a660-15866b88924d.png">

Nope sorry thats wrong, the problem i was having was becuase the repo itself was damaged it wasnt that we werent following the instructions i talked to the devs on discord they fixed the problem and changed some stuff, even the yaml script to save the models was missing before they fixed it dont worry but this is still a necessary step

**Comment by AlexanderKozhevin** [comment]
+1, same

**Comment by elo0i** [comment]
> Guys I found the solution. We aren't following the instructions on the readme well enough.
> 
> 1. Select Pytorch as your template
> 
> <img alt="Screenshot 2023-03-10 at 00 51 16" width="1392" src="https://user-images.githubusercontent.com/46765459/224234430-ea2e884f-d9d7-452a-8722-bffa22e14d69.png">
> 
> 2. Once you create it, edit the pod and remove all the versioning to just say `runpod/pytorch`, this I believe gets the latest version of the image, and voilá your code should run just fine.
> <img alt="Screenshot 2023-03-10 at 00 53 19" width="1084" src="https://user-images.githubusercontent.com/46765459/224234715-988df915-1cdb-4e10-a660-15866b88924d.png">

Thanks! All working now! I forgot to switch to PyTorch in Vast.ai
