### ISSUE TITLE
Upload Images in Dreambooth Training Environment Setup fails on dreambooth_joepenna.ipynb

### ISSUE THREAD

**Issue by devonuto** [JoePenna/Dreambooth-Stable-Diffusion#174]
Uploading training images...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/workspace/Dreambooth-Stable-Diffusion/JupyterNotebookHelpers/setup_training.py in submit_form_click(self, b)
    194                 return
    195             else:
--> 196                 self.handle_training_images(uploaded_training_images)
    197 
    198             # Regularization Images

/workspace/Dreambooth-Stable-Diffusion/JupyterNotebookHelpers/setup_training.py in handle_training_images(self, uploaded_images)
    263         image_widgets = []
    264         for i, img in enumerate(uploaded_images):
--> 265             images.append(img.name)
    266             image_widgets.append(widgets.Image(
    267                 value=img.content,

AttributeError: 'str' object has no attribute 'name'

**Comment by devonuto** [comment]
Just using the training images upload button and selecting a bunch of images and hitting the Save button.

**Comment by yushan777** [comment]
Are you using Runpod?  I've seen this error if you use the `runpod/pytorch-latest` docker image template. Try using the `runpod/pytorch-3.10-1.13.1-116` image instead.

**Comment by devonuto** [comment]
I was using runpod/pytorch:3.10-2.0.0-117

**Comment by devonuto** [comment]
@yushan777 thanks, that seems to have solved it.
