### ISSUE TITLE
Offloading ckpt from vast to googledrive when training is done

### ISSUE THREAD

**Issue by 1blackbar** [JoePenna/Dreambooth-Stable-Diffusion#18]
Hey i had a hard time yesterday setting up gdrive even tho its pretty straightforward there are still permissions in place that cause trouble so i gave up, so eveytthing wehnt fine it accepted my googledrive token but i could not mount it.

I wanted to just move my ckpt into drive , used these instructions on bottom 
https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/5102fccf071fe606429de1bdbdd94357df64a7e2/dreambooth_runpod_joepenna.ipynb

as well as these cause i had that   fuse: bad mount point   runtime 1 error mentioned 
https://stackoverflow.com/questions/61449536/mount-google-drive-from-ai-platform-notebook

You think it will work with vast ? I presume it works for runpod cauise the code is in notebook  ?

**Comment by storods** [comment]
I had the same situation happening and I got it working on Vast.ai

Here's my drag and drop solution for now:
`wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_amd64.tar.gz
tar -xf gdrive_2.1.1_linux_amd64.tar.gz
sudo install gdrive /usr/local/bin/gdrive
apt-get install musl
gdrive list`

With the grdive list you can trigger the auth. After that you just run the upload and it should work fine.

`gdrive upload filetoupload.ckpt`

**Comment by MollerVictor** [comment]
A bit simpler one, works on jupyter but you need to open a terminal and run it there. I haven't figured out a good way of entering the auth key directly from a notebook.
```wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
tar -xvf gdrive_2.1.1_linux_386.tar.gz
./gdrive about
./gdrive upload ./trained_models --recursive
```

**Comment by chelfyn** [comment]
I can't get a clean authorization when I run from a community pod in runpod, but it works with a secure one. any ideas?

**Comment by jmattthew** [comment]
After I install gdrive, and try "gdrive list", it says "Go to the following url in your browser: ..." to authorize.  But entering that url, the page says "Access blocked: project-367116221053’s request is invalid"

**Comment by chelfyn** [comment]
I get this a lot as well. It's about 50/50 whether the gdrive download
works for me. I think it may be dependent on the runpod instance.

Chelfyn Baxter
Creative Director
mohawkmedia.co.nz <http://mowhawkmedia.co.nz>
