### ISSUE TITLE
"No training images provided" error

### ISSUE THREAD

**Issue by jeekca** [JoePenna/Dreambooth-Stable-Diffusion#182]
Hey guys,

At the "Dreambooth Training Environment Setup" step, I click the orange "Training Images (0)" button, Windows' File Explorer pops up, I select all 26 of my PNG images, then once I press "Open" within the File Explorer, the section's form disappears. So in short, it goes from this:

![dreambooth-img-upload-error_002](https://user-images.githubusercontent.com/9212627/235796794-cc30f422-2dbb-4710-88da-0991a8c922d6.png)

...to this:

![dreambooth-img-upload-error_001](https://user-images.githubusercontent.com/9212627/235796633-0ced940a-8628-49c7-b7e3-7b97ad4bcb0c.png)

...after pressing "Open".

Here's some additional info in list-form:

- I am using the "dreambooth_joepenna.ipynb" notebook
- I am running 1 X RTX A6000 from RunPod.io with 60 GB Disk/Pod Volume
- I've updated the "Docker Image Name" to say `runpod/pytorch`, as instructed in this repo's README.
- The selected images are 26 X PNG files, all named "01.png", "02.png", [...] "26.png" and are all 512px X 512px
- There are no console errors
- I've reproduced this error both in Chrome and Firefox

I've updated the "Docker Image Name" to `runpod/pytorch-3.10-1.13.1-116` as suggested [here](https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/174#issuecomment-1503008301), but I still get the same exact bug.

Any insights?

Thanks a ton!

**Comment by djbielejeski** [comment]
Can you provide your 26 training images so we can reproduce? You can black them out or blur them or whatever, just keep the names the same.

**Comment by jeekca** [comment]
Hey @djbielejeski,

Thanks for the prompt response.

I've attached the training images to this message. Hopefully this helps. I was still able to get my training done through the legacy dreambooth file, but hopefully I get to do my training on the new dreambooth file soon, as it's so much more user-friendly.

Thanks!

[training-images.zip](https://github.com/JoePenna/Dreambooth-Stable-Diffusion/files/11389706/training-images.zip)

**Comment by djbielejeski** [comment]
Looks like the ipwidget FileUpload can only do up to 10mb max (which is incredibly stupid lol).  

We have a couple work arounds

1) Upload 1 image and proceed as normal.  After the config is generated all you have to do is upload your remaining training images to the training_images folder.
2) Compress your input images to stay under the 10mb file limit by using jpegs.  You shouldn't notice any quality loss.

**Comment by jeekca** [comment]
@djbielejeski Thank you so much for the prompt assistance! Now that you mention it, my PNG-s are wildly uncompressed.

It'd be nice to have a little file size indicator or better error message, but at least I can work around the limitation now that I know the cause. I'll go with your suggestions.

Thanks a ton once again!

**Comment by brunobpsrpg** [comment]
> 

Idk if it helps, but i always put my pngs on BIRME, this will compress and resize the files for you.
Hope it helps.

https://www.birme.net/?target_width=512&target_height=512
