### ISSUE TITLE
Establish a baseline with a sample set of training images

### ISSUE THREAD

**Issue by toyssamurai** [JoePenna/Dreambooth-Stable-Diffusion#186]
It will be very helpful for beginners like me if your guide includes a sample set of traning images and a sample configuration. If we can use the same set of samples images and configuration to train, then we can verify our trained model to see if it can produce the same level of result as yours does.

**Comment by yushan777** [comment]
Understood. However there is a privacy issue with using and sharing real people's faces - although Joe has allowed others to use his face for training in the past. Perhaps it can be done with an artstyle, or a face that's available in the public domain (but isn't a known celebrity). I'll try and add that when I have a bit of time.   Even if you are able to reproduce what someone else can with their dataset, using your own will be a different experience.  I've had to go back and curate my datasets many times over, training again and again until the model was able to reproduce the subject's likeness well and was flexible enough to be styled and used in different contexts.
