### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled (+Another Issue)

### ISSUE THREAD

**Issue by bazookablue** [JoePenna/Dreambooth-Stable-Diffusion#20]
Hey! So I've been trying to figure this out for a bit, I'm a bit new to the whole process. I'm using Jupyter notebook to run the runpod cells and I've basically gotten to the training but after a few seconds of running that cell I receive the following error:

![image](https://user-images.githubusercontent.com/54251811/193323860-f706f93f-5525-4c17-9b23-dd75ca906089.png)

I've done a bit of google search and can't quite find anything to help me in this situation. Thanks for the help in advanced!

**Comment by Waner-Rodrigues** [comment]
Hey bazooka, did you fixed the error? I am getting the same, and I tried everything I could find to fix it and nothing worked

**Comment by Vermorxt** [comment]
You need to install the latest torch version to fix the Cuda issue:

```
pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html
```

https://github.com/pytorch/pytorch/issues/30664#issuecomment-757431613

**Comment by GITAccountForAIdl** [comment]
Thank you, Vermorxt. I got that 'AssertionError' after I tried to run a newly (to me) installed ComfyUI, which was after I had installed Cuda and CuDNN. Your solution worked (whereas numerous other solutions that I read about did not).

> Vermorxt commented:
> You need to install the latest torch version to fix the Cuda issue:
> pip uninstall torch
> pip cache purge
> pip install torch -f https://download.pytorch.org/whl/torch_stable.html
