### ISSUE TITLE
UnidentifiedImageError: crashing download of images 

### ISSUE THREAD

**Issue by Airburner** [JoePenna/Dreambooth-Stable-Diffusion#24]
Hey I have error: 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f0981e1e950>

When I try to load images to train the model

**Comment by Airburner** [comment]
UnidentifiedImageError                    Traceback (most recent call last)
Cell In [35], line 26
     23   return None
     24  return Image.open(BytesIO(response.content)).convert("RGB")
---> 26 images = list(filter(None,[download_image(url) for url in urls]))
     27 save_path = "./training_samples"
     28 if not os.path.exists(save_path):

Cell In [35], line 26, in <listcomp>(.0)
     23   return None
     24  return Image.open(BytesIO(response.content)).convert("RGB")
---> 26 images = list(filter(None,[download_image(url) for url in urls]))
     27 save_path = "./training_samples"
     28 if not os.path.exists(save_path):

Cell In [35], line 24, in download_image(url)
     22 except:
     23  return None
---> 24 return Image.open(BytesIO(response.content)).convert("RGB")

File /venv/lib/python3.8/site-packages/PIL/Image.py:3008, in open(fp, mode, formats)
   3006 for message in accept_warnings:
   3007     warnings.warn(message)
-> 3008 raise UnidentifiedImageError(
   3009     "cannot identify image file %r" % (filename if filename else fp)
   3010 )

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f0981e1e950>

**Comment by jchirik** [comment]
Try restarting the kernel? Worked for me

**Comment by Airburner** [comment]
Thanks, I think that changing file location from Gdrive to Dropbox helped.

**Comment by a-straus** [comment]
> Thanks, I think that changing file location from Gdrive to Dropbox helped.

Hey, wondering what you meant by this? That you were hosting your files on Dropbox but changed the URLs to Gdrive and that got you past this error? I'm having the same error hosting my photos on imgur

**Comment by Airburner** [comment]
Yes, it was problem with img hosting server and link, now I am using dropbox and it's ok!
