### ISSUE TITLE
Re-using the environment for a 2nd training session

### ISSUE THREAD

**Issue by ozzeruk** [JoePenna/Dreambooth-Stable-Diffusion#29]
I've been experimenting to determine what exactly is required to repeat the process having just completed training one set of photos.

Right now I do one person, wait for it to finish, get my pruned checkpoint file, beautiful!

Now.... I have a new set of photos for a different person, and I want to create a model checkpoint file for them.

It appeared that the base checkpoint file isn't changed, so reverting that doesn't seem necessary?

Then I repeated the training step - but got an error related to dataset - I then tried repeating the earlier personalisation step - but note - during this test I was using the same object name. I haven't yet tried using a different object name.

Do we have a logical series of steps required to in effect revert the training and get the environment ready for a new series of photos and a new object name?

I'm reporting this as an issue and hope that's okay - currently there's no mention anywhere on the script about being able to repeat the process, but I imagine it's something everyone will assume they can do.

Or do I need to start from scratch each time?

**Comment by djbielejeski** [comment]
Just replace your `training_images` and run the training cell again with any other changes youd like to make.
