### ISSUE TITLE
Help using the prune script please.

### ISSUE THREAD

**Issue by ZeroCool22** [JoePenna/Dreambooth-Stable-Diffusion#33]
I have my CKPT i trained here:

![Screenshot_11](https://user-images.githubusercontent.com/13344308/193718209-d6679ab7-5cd1-4a9d-976f-49a6de0e634b.jpg)

And i also put the prune script.py there.

Now how i run it, can someone tell me the correct line with the correct location to run it on CMD or CONDA PROMPT?

Thx in advance!

**Comment by djbielejeski** [comment]
Not applicable to this.

**Comment by ZeroCool22** [comment]
> Not applicable to this.

How this guy run the script then on a CKPT?

https://www.youtube.com/watch?v=_e5ymV4zY3w

**Comment by ZeroCool22** [comment]
> Not applicable to this.

![Screenshot_17](https://user-images.githubusercontent.com/13344308/193725972-c315e3e1-e9e8-4ebe-ba98-a45c2c0d4dca.jpg)

Worked i guess...
