### ISSUE TITLE
After training is finished, it restarts another training ? 

### ISSUE THREAD

**Issue by Mozoloa** [JoePenna/Dreambooth-Stable-Diffusion#35]
As the title says, when you're done training for a set of pictures, it just starts again in a loop

**Comment by Wizard-Battle** [comment]
I had this happen to me as well when I changed the steps to 9999 to see what would happen. After it reached 2020 steps it started again and I assumed it was trying to reach 9999 steps and was being displayed in the notebook as chunks of 2020

**Comment by Mozoloa** [comment]
well I hope you had something else productive to do in the mean time haha, must have been long

**Comment by djbielejeski** [comment]
What is being written to the UI is steps for a Epoch.  An epoch length is `training_images_count * 101`. An epoch's length doesn't matter, just total step count. So if you have 10 training images training for 2000 steps, you will have an epoch length of 1010, and it will get most of the way through the second epoch.  It is not restarting training, just continuing on.

**Comment by Mozoloa** [comment]
That's not the problem, this has been discussed before.

Regardless of the epoch length, for instance at 1500 steps 10 pics, it was 1010/1010 + another one 490/1010, it should have then stopped, it did but it started a whole other one right after, this only happened once but I saw many people reporting it so I thought opening an issue was in order
