### ISSUE TITLE
Multiple persons

### ISSUE THREAD

**Issue by K4CZP3R** [JoePenna/Dreambooth-Stable-Diffusion#36]
Is it possible to train a model containing two persons?

**Comment by ozzeruk** [comment]
I would like to know the answer to this too.

I currently have 8 different 2GB model files, which all work really nicely. I wonder if it's possible to combine them and not risk losing data for any of them.

**Comment by eadnams22** [comment]
I think, if you don't prune the new ckpt files, you can just train with one of those as your next  --actual_resume path, since the unpruned one contains all of the master weight ckpt files data.

Gonna do some tests and see!

**Comment by thegenerativegeneration** [comment]
I tried that but the people became increasingly distorted with each new training/person added.

I'm trying this approach now https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/issues/12 but that so far still ends up with just one person in the model.

**Comment by eadnams22** [comment]
> 

Hmm, yeah, I venture they each need to be in different classes, and not over trained? I'm still experimenting too.

**Comment by Jorvan758** [comment]
> > 
> 
> Hmm, yeah, I venture they each need to be in different classes, and not over trained? I'm still experimenting too, but noticing some distortions to the classes over time

Eventually, do us the favour of telling the results of your experiments, pls 🙌

**Comment by eadnams22** [comment]
> 

Seems like diverse enough classes seem to be okay, but man/woman bleed into each other, perhaps all that are close to each other will bleed into nearby classes?

I'd love a list of the noun classes, or a tree of their structure really, to better understand what it might be doing.

**Comment by maderix** [comment]
I actually tried this for two subjects with one class name describing two people in a set of images (eg: a photo of persons xx_yy) . After training the model is able to separate 'xx' and 'yy' as separate entities. Eg 'Male Person xx' and 'female person yy' will produce the proper outputs while still retaining the couple aspect. I didn't observe class bleeding but it could be just my experience.

**Comment by djbielejeski** [comment]
See this discord channel for more discussion on multiple subjects: https://discord.com/channels/1023277529424986162/1034634875782823997
