### ISSUE TITLE
Getting to run JoePenna / Dreambooth-Stable-Diffusion in a 16GB Google Colab

### ISSUE THREAD

**Issue by jslegers** [JoePenna/Dreambooth-Stable-Diffusion#51]
I've currently been using @ShivamShrirao's fork of [huggingface/diffusers](https://github.com/huggingface/diffusers) ([ShivamShrirao/diffusers](https://github.com/ShivamShrirao/diffusers)) and I've been running this perfectly fine with [my own finetuned Google Colab notebook](https://colab.research.google.com/github/jslegers/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb).

Is there someone who can tweak this repo so it can run on 16GB VRAM as well? Or, since I'm especially interested in @kanewallmann's addition for support for multiple concepts & classes ([kanewallmann/Dreambooth-Stable-Diffusion](https://github.com/kanewallmann/Dreambooth-Stable-Diffusion), is there someone who can port that feature to [huggingface/diffusers](https://github.com/huggingface/diffusers) ([ShivamShrirao/diffusers](https://github.com/ShivamShrirao/diffusers))?

Related :

- https://github.com/ShivamShrirao/diffusers/issues/21
- https://github.com/huggingface/diffusers/issues/752

**Comment by djbielejeski** [comment]
Shivam's repo is diffuser based, not sure what it would take to get some of those optimizations in this repo.

**Comment by jslegers** [comment]
@djbielejeski :

So you just close the issue as "completed"? That's not very helpful / useful...

So, I guess this version of Dreambooth is not diffusers based? Could you enlighten us on how it is implemented, then? Maybe this could shed a light on potential optimisations...
