### ISSUE TITLE
Model doesn't show up at the end of training when using Copy and Name cell

### ISSUE THREAD

**Issue by Strothis** [JoePenna/Dreambooth-Stable-Diffusion#54]
Instead I get this error message and nothing in traned_models
![Screenshot 2022-10-06 191002](https://user-images.githubusercontent.com/107116713/194376474-df4bbb3a-d4bb-4c76-ae40-6866956f9fbb.png)

**Comment by djbielejeski** [comment]
Yeah we have a bug with filenames in the copy script if you use spaces as your token, we'll get a fix in. @fabbarix is this something you can help with?

**Comment by djbielejeski** [comment]
This has been resolved
