### ISSUE TITLE
gdrive not working

### ISSUE THREAD

**Issue by smaga38** [JoePenna/Dreambooth-Stable-Diffusion#70]
I launched the `dreambooth_runpod_joepenna.ipynb`, but could not log in to gdrive. after executing the request and opening the generated link in the browser, I see this:

`The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method`

**Comment by matthias-kubicki-CES** [comment]
I was linked to this docu page: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by Adakinara** [comment]
![image](https://user-images.githubusercontent.com/106352192/198107468-744a300f-50d3-44a7-bcc9-2187721f70bd.png)

**Comment by Adakinara** [comment]
A workaround using another repo:

download credentials from google console, call it `"credentials.json`"

`pip3 install --upgrade gupload` to install the repo

create a folder in Gdrive and "share" it public

Copy the ID of the folder

`gupload --to FOLDERIDHERE --file nameofthefileyouaresavingas.ckpt /workspace/Dreambooth-Stable-Diffusion/trained_models/nameofthefiletoupload.ckpt`

**Comment by metzo007** [comment]
> A workaround using another repo:
> 
> download credentials from google console, call it `"credentials.json`"
> 
> `pip3 install --upgrade gupload` to install the repo
> 
> create a folder in Gdrive and "share" it public
> 
> Copy the ID of the folder
> 
> `gupload --to FOLDERIDHERE --file nameofthefileyouaresavingas.ckpt /workspace/Dreambooth-Stable-Diffusion/trained_models/nameofthefiletoupload.ckpt`

why do I need to download the credentials? It looks like I never use them later.

**Comment by Lalimec** [comment]
got this error, where do i put the json file?
![ss_221030235700](https://user-images.githubusercontent.com/65521426/198901172-50ffda78-3f23-4331-8139-76ef93ec31c7.jpg)
