### ISSUE TITLE
docs clarification: token "leaks" into class?

### ISSUE THREAD

**Issue by jmp909** [JoePenna/Dreambooth-Stable-Diffusion#73]
regarding this section:
https://github.com/JoePenna/Dreambooth-Stable-Diffusion#-using-the-generated-model

when you use `Natalie Portman person` it is clearly showing a lot of your `sks` subject, without using `sks` in the prompt. is that because the training images actually "leak" into the class `person`?

thanks.

`sks person`
<img src="https://user-images.githubusercontent.com/100188076/192403506-ab96c652-f7d0-47b0-98fa-267defa1e511.png" width="100">

`Natalie Portman person`
<img src="https://user-images.githubusercontent.com/100188076/192403437-f9a93720-d41c-4334-8901-fa2d2a10fe36.png" width="100">

**Comment by codemonkeynorth** [comment]
Noted this is actually explained in the docs. Closing

**Comment by jmp909** [comment]
Noted this is actually explained in the docs. Leaking does occur throughout the class. Closing
