### ISSUE TITLE
Steps for epoch not set correctly

### ISSUE THREAD

**Issue by caacoe** [JoePenna/Dreambooth-Stable-Diffusion#77]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/110500565/196188533-0db1b9bb-7df9-40e6-a00a-fae195634865.png">

Hey, see the above image.

Seems to be breaking the steps per epoch calculation.

112 training inputs, 1200 class, 400 repeats and it isn't providing the correct number per epoch (even when setting maximum steps absurdly high)

**Comment by djbielejeski** [comment]
From chapel in discord: "Epoch length is the lesser between training images times repeats and reg images times repeats"

Epoch is `# Training Images` * `Repeats` + `# of Training Images`.  

Example: 16 images * 100 repeats (default # of repeats) + 16 images = 1616 steps for 1 epoch when training 16 images.

Repeats location if you want to change it: https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/1642b2db80c1dd6a76d101342963681e16f5d4a0/configs/stable-diffusion/v1-finetune_unfrozen.yaml#L88
