### ISSUE TITLE
Google Colab Support

### ISSUE THREAD

**Issue by bach777** [JoePenna/Dreambooth-Stable-Diffusion#82]
Could be possible to get a Google Colab version

**Comment by swcrazyfan** [comment]
> Could be possible to get a Google Colab version

There is one already, but you'll need to get a good enough GPU. Generally, you rarely get one unless you go for Pro+ for $50/month. You actually get more for $39/month over at Paperspace. You can choose the specific GPU you get and have it for at least 6 hours without issues.

**Comment by JhonSummer** [comment]
@swcrazyfan where is the colab though?

**Comment by shacharco1** [comment]
Yea.. tried to run it. Doesn't work on the free version. Doesn't creat cpkt file

**Comment by djbielejeski** [comment]
Colab version was added a while ago.
