### ISSUE TITLE
Train concept other than person?

### ISSUE THREAD

**Issue by rexroth0619** [JoePenna/Dreambooth-Stable-Diffusion#85]
Newcomer here, may sound like a dumb question -- 
1. How do I train something else other than a person? I notice in regularization images section there is only images for people. Say if I want to train an animal, or mascot of sort, what should I do? Should I first make a judgment on its category (toy, animal, etc) then create my own regularization image dataset?

2. How do I train something intangible like a style? How do I create a regularization dataset for that?

Thank you!

**Comment by Lalimec** [comment]
Got pretty good results with that basic approach. 

![00320-2788875736-a pretty girl annanovik style7chmevna](https://user-images.githubusercontent.com/65521426/198898108-0b5f5712-481a-4053-b6a9-75139e51929e.png)
![luiza-scandelari-598487-fit](https://user-images.githubusercontent.com/65521426/198898110-34c7b4d4-2f4e-46d4-8afc-f266dd48bb7c.jpg)
![02290-775262925-old man gandalf annanovik stylehycka22f](https://user-images.githubusercontent.com/65521426/198898111-ced49acc-09e1-4b65-9828-0f94d992f2d3.png)
![Gandalf-2](https://user-images.githubusercontent.com/65521426/198898114-0eb47351-464e-485f-a375-548df889b71a.jpg)
![tmphcy9c22d](https://user-images.githubusercontent.com/65521426/198898115-9785012f-7fca-4462-8877-cc14035cbf28.png)
![Scarlett-Johansson-Disney-Lawsuit](https://user-images.githubusercontent.com/65521426/198898116-96f5456a-f599-4c47-a0aa-b3e863613c4d.jpg)
![02296-4286988364-bella hadid annanovik styleyyq63lew](https://user-images.githubusercontent.com/65521426/198898118-1c9d534d-c4e6-4270-8344-6be621e90673.png)
![663191-986852759 (2)](https://user-images.githubusercontent.com/65521426/198898119-4657b0bf-7e70-4ee8-9a8c-a72c9b12ce9e.jpg)
![00401-472641974-dua lipa annanovik style, detailed eyes, detailed iris3wcdo7y7](https://user-images.githubusercontent.com/65521426/198898120-d0f47836-6708-4827-9e74-5f7dbe3903db.png)
![629faca27a1fe3a15f076364](https://user-images.githubusercontent.com/65521426/198898123-e91e058b-06b8-4449-92bb-d9f39a7373a4.jpg)
