### ISSUE TITLE
Error on Paperspace

### ISSUE THREAD

**Issue by bairasky** [JoePenna/Dreambooth-Stable-Diffusion#87]
※I am not an engineer and English is not my first language. Sorry if some parts are hard to understand.

I am trying to run it in Paperspace, but at the time of starting the training, I get an error that does not occur in Vast.ai.

Environment
・Runtime template is Pytorch 1.12
・Selected A6000

First Error

> Global seed set to 23
> Running on GPUs 0,
> Loading model from model.ckpt
> Traceback (most recent call last):
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 683, in <module>
>     model = load_model_from_config(config, opt.actual_resume)
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 33, in load_model_from_config
>     model = instantiate_from_config(config.model)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/util.py", line 87, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/util.py", line 95, in get_obj_from_str
>     return getattr(importlib.import_module(module, package=None), cls)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 26, in <module>
>     from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/models/autoencoder.py", line 6, in <module>
**>     from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
> ModuleNotFoundError: No module named 'taming'**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 896, in <module>
>     if trainer.global_rank == 0:
> NameError: name 'trainer' is not defined

I took the bolded part as a hint.
Dreambooth-Stable-Diffusion/src/taming-transformers/taming/modules/vqvae/quantize.py　is exists.

But it didn't seem to load, so I installed it again with the following command
`!pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers`

The execution result is as follows.

> Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
>   Updating ./src/taming-transformers clone (to revision master)
>   Running command git fetch -q --tags
>   Running command git reset --hard -q 24268930bf1dce879235a7fddd0b2355b84d7ea6
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: torch in /usr/local/lib/python3.9/dist-packages (from taming-transformers) (1.12.0+cu116)
> Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from taming-transformers) (1.23.1)
> Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from taming-transformers) (4.64.0)
> Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from torch->taming-transformers) (4.3.0)
> Installing collected packages: taming-transformers
>   Running setup.py develop for taming-transformers
> Successfully installed taming-transformers-0.0.1
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

I started the training again and another error occurred.

> Global seed set to 23
> Running on GPUs 0,
> Loading model from model.ckpt
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> making attention of type 'vanilla' with 512 in_channels
> Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
> making attention of type 'vanilla' with 512 in_channels
> Traceback (most recent call last):
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 683, in <module>
>     model = load_model_from_config(config, opt.actual_resume)
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 33, in load_model_from_config
>     model = instantiate_from_config(config.model)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/util.py", line 87, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 476, in __init__
>     self.instantiate_cond_stage(cond_stage_config)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/models/diffusion/ddpm.py", line 559, in instantiate_cond_stage
>     model = instantiate_from_config(config)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/util.py", line 87, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/util.py", line 95, in get_obj_from_str
>     return getattr(importlib.import_module(module, package=None), cls)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/notebooks/Dreambooth-Stable-Diffusion/ldm/modules/encoders/modules.py", line 4, in <module>
>     import clip
**> ModuleNotFoundError: No module named 'clip'**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 896, in <module>
>     if trainer.global_rank == 0:
> NameError: name 'trainer' is not defined
> 

Again, I ran the following command, referring to the bolded part.
`!pip install clip`

The execution result is as follows.

> Collecting clip
>   Downloading clip-0.2.0.tar.gz (5.5 kB)
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: clip
>   Building wheel for clip (setup.py) ... done
>   Created wheel for clip: filename=clip-0.2.0-py3-none-any.whl size=7005 sha256=014c8b15686df1dd8688cb97b2ff0ea1811648b65e4a6fc46634ebaed9b28d88
>   Stored in directory: /root/.cache/pip/wheels/8f/99/44/ceb6f1b57fd1a1d7241d886a4074ffbd552937ed87ccf479d6
> Successfully built clip
> Installing collected packages: clip
> Successfully installed clip-0.2.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Start training again. It seems to be going well, but in the second half of the training, the following error occurs

> 
> Lightning config
> modelcheckpoint:
>   params:
>     every_n_train_steps: 500
> callbacks:
>   image_logger:
>     target: main.ImageLogger
>     params:
>       batch_frequency: 500
>       max_images: 8
>       increase_log_steps: false
> trainer:
>   benchmark: true
>   max_steps: 3000
>   gpus: 0,
> 
> Sanity Checking: 0it [00:00, ?it/s]/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/data.py:127: UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
>   rank_zero_warn(
> Here comes the checkpoint...       
> Prunin' Checkpoint
> Checkpoint Keys: dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers'])
> Removing optimizer states from checkpoint
> This is global step 0.
> Training complete. max_training_steps reached or we blew up.
> Traceback (most recent call last):
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 875, in <module>
>     trainer.fit(model, data)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
>     self._call_and_handle_interrupt(
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
>     results = self._run(model, ckpt_path=self.ckpt_path)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
>     results = self._run_stage()
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
>     return self._run_train()
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
>     self.fit_loop.run()
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/base.py", line 199, in run
>     self.on_run_start(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
>     self.trainer.reset_train_dataloader(self.trainer.lightning_module)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1856, in reset_train_dataloader
>     self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING, model=model)
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 459, in _request_dataloader
>     dataloader = source.dataloader()
>   File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 536, in dataloader
>     return method()
>   File "/notebooks/Dreambooth-Stable-Diffusion/main.py", line 300, in _train_dataloader
>     return DataLoader(train_set, batch_size=self.batch_size,
>   File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 347, in __init__
>     sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
>   File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0

ValueError: num_samples should be a positive integer value, but got num_samples=0
I cannot determine the cause of this error. 
The folder training_images contains images.

**Comment by cantaspinar** [comment]
Did you figure out what was the issue?

**Comment by bairasky** [comment]
No, it's not resolved.

**Comment by 0xdevalias** [comment]
Potentially related (`NameError: name 'trainer' is not defined`):

- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/28
- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/53
- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/86
- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/87

**Comment by Erpix3lt** [comment]
Has this been resolved yet? Getting the same error ..

**Comment by Samvid95** [comment]
Yup I am also getting the same error

**Comment by bairasky** [comment]
Resolved.
In JoePenna's notebook,root path is "workspace", but in Paperspace it is "notebooks".
This is why the training images could not be referenced.
Rewriting the path in the notebook solves the problem.
