### ISSUE TITLE
NameError: name 'dataset' is not defined

### ISSUE THREAD

**Issue by RyanKelly-DC** [JoePenna/Dreambooth-Stable-Diffusion#9]
Thanks for this. Works well with an a5000, had issues with other Nvidia GPUs. Running into this issue in the training step, any fixes or ways to avoid it? 

> NameError                                 Traceback (most recent call last)
> Cell In [10], line 10
> 
> ---> 10 reg_data_root = "/workspace/Dreambooth-Stable-Diffusion/outputs/txt2img-samples/samples/" + dataset
> 
> NameError: name 'dataset' is not defined

This happens if you generate your own regularization set instead of using the repos, I assume because you skip this cell in doing so:

> # Grab the existing regularization images
> # Choose the dataset that best represents what you are trying to do and matches what you used for your token
> # man_euler, man_unsplash, person_ddim, woman_ddim
> dataset="person_ddim"
> !git clone https://github.com/djbielejeski/Stable-Diffusion-Regularization-Images-{dataset}.git
> 
> !mkdir -p outputs/txt2img-samples/samples/{dataset}
> !mv -v Stable-Diffusion-Regularization-Images-{dataset}/{dataset}/*.* outputs/txt2img-samples/samples/{dataset}

**Comment by EliEron** [comment]
When you generate your own images they are dumped directly into "outputs/txt2img-samples/samples" regardless of what your prompt is. So the correct solution is to simply remove "+ dataset" from line 10 of the cell.

**Comment by RyanKelly-DC** [comment]
Thanks all

**Comment by greendesertsnow** [comment]
Then I get these errors
```
mv: cannot stat 'Stable-Diffusion-Regularization-Images-person_ddim/person_ddim/.': No such file or directory
```
```
IsADirectoryError: [Errno 21] Is a directory: '/workspace/Dreambooth-Stable-Diffusion/outputs/txt2img-samples/samples/person_ddim' 
```
