### ISSUE TITLE
How to export ckpt file to run locally?

### ISSUE THREAD

**Issue by slives-lab** [JoePenna/Dreambooth-Stable-Diffusion#99]
Regarding the Hugging Face Diffusers - Alternate Option (Dreambooth is now supported in HuggingFace Diffusers for training with Stable Diffusion) in google colab. How can the ckpt file be exported to run locally?

**Comment by 0xdevalias** [comment]
There are steps in the notebook for uploading the ckpt file to Google Drive. That same ckpt file is what you would need to use to run it locally.

**Comment by slives-lab** [comment]
> There are steps in the notebook for uploading the ckpt file to Google Drive. That same ckpt file is what you would need to use to run it locally.

If you can specify the steps in the notebook to upload the clot file to google drive that would be helpful. Thanks

**Comment by 0xdevalias** [comment]
Literally the last section of the notebook..? https://github.com/JoePenna/Dreambooth-Stable-Diffusion/blob/main/dreambooth_colab_joepenna.ipynb

![image](https://user-images.githubusercontent.com/753891/200231288-9816986f-78b8-4cee-8977-160ff3eac415.png)
